### ISSUE TITLE
AODCS Pointing Requirement

### ISSUE THREAD

**Issue by SeanTedesco** [queens-satellite-team/payload#7]
## Introduction
AODCS is required to know the pointing accuracy as required by the PAYLOAD. While the PAYLOAD will want to have a pointing error of zero, it is infeasible for AODCS to achieve this. We then must determine what is the maximum pointing error that is still acceptable for all PAYLOAD requirements.

## Supporting Information 📖 

Factors to go into this internal pointing requirement include:
- Minimizing Motion Blur
- Ensuring ARO is still in the image captured by the PAYLOAD. 
- Feedback from the CSDC regarding the PAYLOAD included: “If the ground blur is less than ½ a pixel, It’s irrelevant”. 
- CSDC Requirement: TO BE INCLUDED

## Next Steps 🚶 

What we have to determine:
- Field of View
- Pixel Size

## Definition of Done 💯 
_An angle specified in degrees that will minimize ground blur and ensure the ARO is within the field of view of the PAYLOAD._

cc: @kateszabo @emmapaczkowski @SeanTedesco

**Comment by matthewuhthoff** [comment]
Issue solved for CDR, will re-open if needed based on feedback
