### ISSUE TITLE
PAYLOAD Volume Requirement

### ISSUE THREAD

**Issue by SeanTedesco** [queens-satellite-team/payload#9]
## Introduction
PAYLOAD wants to maximize its volume in the spacecraft; however, spacecraft volume is severely constrained. We shall determine if a set volume of ½ the spacecraft volume is sufficient to provide the required optical parameters for the Selfie-Sat mission.

Note: There is also a slightly different way we can approach this which may take longer, but would lead to a more optimal design. Instead of starting with a volume, we make this a variable and attempt to find the minimum volume required to allow for the required optics. The definition of done questions would then be something along the lines of: _Answer: “What is the minimum volume required assuming a refracting lens configuration (Keplerian telescope)?”_  and _Answer: “What is the minimum volume required assuming a refracting lens configuration (Galilean telescope)?”_

## Supporting Information 📖 

Factors to go into determining PAYLOAD volume requirement:
- Focal Lengths
- Lens Diameters
- Assume available volume is ½ spacecraft volume: 9cm x 9cm x 17cm 
- CSDC Requirement: TO BE INCLUDED

## Next Steps 🚶 

What we have to determine:
- Lens Diameter
- Field of View
- Ground Spatial Distance
- Magnification

## Definition of Done 💯 

1. _Answer: "Will a Keplerian telescope constrained to ½ the spacecraft volume provide sufficient optical parameters for the camera?"_

2. _Answer: "Will a Galilean telescope constrained to ½ the spacecraft volume provide sufficient optical parameters for the camera?"_

cc: @kateszabo @emmapaczkowski @SeanTedesco

**Comment by matthewuhthoff** [comment]
Issue solved for CDR, will reopen based on CDR feedback
